### ISSUE TITLE
iOS app crashes on signing in with google.

### ISSUE THREAD

**Issue by nouveau-riche** [nouveau-riche/smart_kaksha#1]
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(google_sign_in, Your app is missing support for the following URL schemes: com.googleusercontent.apps.702288552178-8n2ao191aobg1f1et19fbibkl999t4km, NSInvalidArgumentException)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
#4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
#5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:42)
<asynchronous suspension>
#6      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:297:16)
#<…>

**Comment by nouveau-riche** [comment]
solved by adding reverse-client-id in URL types in Xcode.
